-- CRM schema cleanup migration
-- Generated by Cursor agent based on user requirements.
-- Safe-ish, but review before applying to production.

begin;

-- 0) Extensions (for gen_random_uuid, etc.)
create extension if not exists pgcrypto;

-- 1) consents: customer_id NOT NULL + UNIQUE + PRIMARY KEY
-- Remove invalid rows first (null customer_id) to avoid constraint failures.
delete from public.consents where customer_id is null;

-- Deduplicate customer_id if duplicates exist (keep one arbitrary row).
-- consents has no PK currently; use ctid to keep the first.
delete from public.consents c
using public.consents c2
where c.customer_id = c2.customer_id
  and c.ctid > c2.ctid;

alter table public.consents
  alter column customer_id set not null;

-- Add UNIQUE and PK (PK implies unique, but keeping explicit UNIQUE is fine if you prefer just PK remove UNIQUE line)
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'consents_customer_id_key'
      and conrelid = 'public.consents'::regclass
  ) then
    alter table public.consents add constraint consents_customer_id_key unique (customer_id);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where contype = 'p'
      and conrelid = 'public.consents'::regclass
  ) then
    alter table public.consents add constraint consents_pkey primary key (customer_id);
  end if;
end $$;


-- 2) notes:
-- 2-1) rename content -> note
-- If both exist or content missing, this may fail; assume current schema has content.
do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'notes'
      and column_name = 'content'
  ) and not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'notes'
      and column_name = 'note'
  ) then
    alter table public.notes rename column content to note;
  end if;
end $$;

-- 2-2) note_type: text -> enum
do $$
begin
  if not exists (select 1 from pg_type where typname = 'note_type_enum') then
    create type public.note_type_enum as enum ('call', 'meeting', 'email', 'follow_up', 'other');
  end if;
end $$;

-- Set existing note_type values to 'other' before type conversion
update public.notes
set note_type = 'other'
where note_type is null
   or note_type not in ('call', 'meeting', 'email', 'follow_up', 'other');

alter table public.notes
  alter column note_type type public.note_type_enum
  using note_type::public.note_type_enum;


-- 3) customers:
-- 3-1) created_at NOT NULL + default now()
alter table public.customers
  alter column created_at set default now();

update public.customers
set created_at = now()
where created_at is null;

alter table public.customers
  alter column created_at set not null;

-- 3-2) updated_at column + trigger
alter table public.customers
  add column if not exists updated_at timestamptz;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_customers_set_updated_at on public.customers;
create trigger trg_customers_set_updated_at
before update on public.customers
for each row
execute function public.set_updated_at();

-- 3-3) phone_number CHECK (allow 010-1234-5678 OR digits only length 10~11)
-- Normalize existing obvious digits-only? (leave as-is; just allow both)
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'customers_phone_number_check'
      and conrelid = 'public.customers'::regclass
  ) then
    alter table public.customers
      add constraint customers_phone_number_check
      check (
        phone_number ~ '^[0-9]{10,11}$'
        or phone_number ~ '^[0-9]{2,3}-[0-9]{3,4}-[0-9]{4}$'
      );
  end if;
end $$;


-- 4) RLS enable + dev policies (authenticated can CRUD all)
alter table public.customers enable row level security;
alter table public.consents enable row level security;
alter table public.notes enable row level security;

drop policy if exists dev_authenticated_all on public.customers;
create policy dev_authenticated_all
on public.customers
for all
to authenticated
using (true)
with check (true);

drop policy if exists dev_authenticated_all on public.consents;
create policy dev_authenticated_all
on public.consents
for all
to authenticated
using (true)
with check (true);

drop policy if exists dev_authenticated_all on public.notes;
create policy dev_authenticated_all
on public.notes
for all
to authenticated
using (true)
with check (true);


-- 5) Indexes
-- consents.customer_id: PK already implies index, but create if missing (no-op if exists)
create index if not exists idx_consents_customer_id on public.consents(customer_id);
create index if not exists idx_notes_customer_id on public.notes(customer_id);

-- customers.phone_number unique already implies index; keep explicit request
create index if not exists idx_customers_phone_number on public.customers(phone_number);
create index if not exists idx_customers_email on public.customers(email);

commit;

